---
- name: Deploy LAMP Stack on Slave Node
  hosts: Slave
  become: yes
  tasks:
    - name: Copy the deploy.sh script
      copy:
        src: /root/lamp_deploy/deploy.sh
        dest: /tmp/deploy.sh
        mode: 0755

    - name: Execute the deploy.sh script
      command: bash /tmp/deploy.sh
    
    - name: Check Server Uptime
      cron:
        name: "Check Server Uptime"
        minute: 0
        hour: 0
        job: "uptime >> /var/log/server_uptime.log"
